# Generated by Django 5.2.3 on 2025-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='presio_total',
            new_name='precio_total',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='presio_unitario',
            new_name='precio_unitario',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
