# Generated by Django 5.2.3 on 2025-07-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0002_rename_presio_total_producto_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
