# Generated by Django 5.2.3 on 2025-07-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0003_alter_producto_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='product',
        ),
    ]
