# Generated by Django 5.2.3 on 2025-07-08 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0005_producto_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='update',
        ),
        migrations.AddField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
