# Generated by Django 5.2.3 on 2025-07-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0006_remove_producto_update_producto_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
