# Generated by Django 5.2.3 on 2025-07-08 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='update',
        ),
        migrations.AddField(
            model_name='metodo_pago',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='metodo_pago',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
