# Generated by Django 5.2.3 on 2025-07-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0002_remove_pedido_update_metodo_pago_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo_pago',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metodo_pago',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
