# Generated by Django 5.2.3 on 2025-07-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0007_alter_producto_updated'),
        ('pedidosApp', '0003_alter_metodo_pago_created_alter_metodo_pago_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(to='inventarioApp.producto'),
        ),
    ]
