# Generated by Django 5.2.3 on 2025-07-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0005_remove_pedido_cantidad_remove_pedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='metodos_pago',
        ),
        migrations.AddField(
            model_name='metodo_pago',
            name='valor',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
