# Generated by Django 5.2.3 on 2025-07-28 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0006_remove_pedido_metodos_pago_metodo_pago_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodo_pago_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidosApp.metodo_pago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodo_pago', to='pedidosApp.pedido')),
            ],
        ),
    ]
