# Generated by Django 5.2.3 on 2025-07-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0007_metodo_pago_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodo_pago',
            name='valor',
        ),
    ]
