# Generated by Django 5.2.3 on 2025-07-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0008_remove_metodo_pago_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodo_pago_pedido',
            options={'verbose_name': 'metodo_pago_pedido', 'verbose_name_plural': 'metodos_pago_pedido'},
        ),
    ]
