# Generated by Django 5.2.3 on 2025-07-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0009_alter_metodo_pago_pedido_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo_pago_pedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodo_pago_pedido', to='pedidosApp.pedido'),
        ),
    ]
