# Generated by Django 5.2.3 on 2025-07-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0010_alter_metodo_pago_pedido_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodo_pago_pedido',
            options={},
        ),
    ]
